### ISSUE TITLE
pytest-valgrind ignores --errors-for-leak-kinds

### ISSUE THREAD

**Issue by thedrow** [seberg/pytest-valgrind#2] opened 2020-09-06 14:19 UTC
I only want definite leaks to error the test suite but for some reason when I run:
```
PYTHONMALLOC=malloc valgrind --errors-for-leak-kinds=definite --leak-check=full --show-leak-kinds=definite --log-file=/tmp/valgrind-output --gen-suppressions=all python -m pytest -vv --valgrind --valgrind-log=/tmp/valgrind-output
```

I still get an error for:
```
[VALGRIND LEAK]

Valgrind has detected a memory leak:

**426713**
**426713** **********************************************************************
**426713** test/test_argparse.py::TestParseItem::test_i[universal]
**426713** **********************************************************************
==426713== LEAK SUMMARY:
==426713==    definitely lost: 0 (+0) bytes in 0 (+0) blocks
==426713==    indirectly lost: 64 (+64) bytes in 1 (+1) blocks
==426713==      possibly lost: 6,861,070 (+711,219) bytes in 65,685 (+5,972) blocks
==426713==    still reachable: 15,205,349 (+763,687) bytes in 121,811 (+6,949) blocks
==426713==         suppressed: 136 (+104) bytes in 2 (+1) blocks
==426713== Reachable blocks (those to which a pointer was found) are not shown.
==426713== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==426713==
**426713**
**426713** *********************************************************************
```

Can you please assist?

**Comment by seberg** [comment] 2020-09-06 15:18
Not sure, my guess is that this is a valgrind setting/definition. I think "indirectly lost" is also lost definitely, but it is lost because a "definitely lost" block elsewhere? I am a bit surprised this shows up on its own though, is there an earlier "definitely lost"?  If not, maybe check the full valgrind output? I am not immediately sure the pytest plugin will show errors that happen between tests, and if this is related to when the python garbage collector runs, it seems plausible that the actual error is only detected between two tests.

If that doesn't help, would you be able to share the program so I could run the test suit myself?  Another try might be to just run the individual test with pytest to narrow it down?

**Comment by seberg** [comment] 2020-09-06 16:14
Ah, sorry, you are right, the way I did it in `pytest-valgrind` is to use the valgrind macro:
```
VALGRIND_COUNT_LEAKS(leaked, dubious, reachable, suppressed);
```
and if `leaked` if that changed, I report it.

So I think you are probably right, `pytest-valgrind` is overzealous with regard to "indirect" leaks right now. `pytest-valgrind` should possibly only rely on `VALGRIND_COUNT_ERRORS` to decide whether an error occurred, although I guess that may mean we can't distinguish memory errors from access error quite as easily.

**Comment by thedrow** [comment] 2020-09-06 16:34
I hope there's a way to resolve this issue.
It's not that big of a problem if there isn't, but maybe we should document it.

Could we check if `leaked == number_of_errors`?

**Comment by seberg** [comment] 2020-09-07 00:25
Something like that should work, I think there is currently a spurious `VALGRIND_COUNT_ERRORS` in the `do_leak_check` C-Function.  And I can just count the errors before and after the leak check, and additionally to the total number of leaks, report the "leak errors" (or even only report the leak errors).

@thedrow do you have a simple test for this to try it out? I am a bit unsure why you would prefer to hide indirect leaks, since it sounds like they are usually real leaks to me? (On the other hand, you are right, you set up valgrind to ignore them for whatever reason and pytest-valgrind should honor that.)

**Comment by seberg** [comment] 2020-09-07 04:30
@thedrow I think this is what you want: gh-3 (at least roughly), the main issue is that you pretty much must use the `--errors-for-leak-kinds=definite` option (which I was probably not aware existed when first writing this).  The problem is that the default includes "possible" leaks, which at least in my quick test creates a lot of false positives...

**Comment by seberg** [comment] 2020-09-07 22:44
@thedrow, OK, I found a somewhat hackish solution, and merged it (see gh-4).

To clarify the issue (aside from me not realizing that this option would have solved this problem).  Python always causes "possible" leaks, and by default valgrind reports those, if you use `--errors-for-leak-kinds=definite` that is not a problem. But since I did not realize that, I manually counted leaks instead :/.
Now, because I am not sure that it makes sense to just switch over and break existing work flows, I opted to probe the behaviour, if `obj = object()` reports a memory leak error, then I use the current behaviour. If it does not report an error, I use the errors as reported by valgrind.  So this allows you to use: `-errors-for-leak-kinds=definite`.

Please let me know if this fixes your issue!

**Closed as completed by seberg** 2020-09-07 22:44 UTC
